exp_name: crop128_5r

train:
  lr: 0.002
  lr_cam: 0.0001
  max_epochs: 10
  num_primarys: 1000
  num_backups: 0
  tile_size: 16
  densification_start: 1000
  densification_interval: -2
  densification_th: 0.005
  model: fix_gauss
  codebook_start: 0
  init_rgb: 1
  color_bias: 0.01
  refine_camera: 1
  batch_size: 16

loss:
  w_l1: 0
  w_masked_l1: 1
  w_bg_l1: 1
  w_l2: 1
  w_masked_l2: 0
  w_bg_l2: 0
  w_mdp_l1: 0
  w_mdp_masked_l1: 1
  w_mdp_bg_l1: 1
  w_mdp_l2: 1
  w_mdp_masked_l2: 0
  w_mdp_bg_l2: 0

  w_rho: 0
  w_radius: 0
  w_mi: 0
  w_cos: 0

process:
  bg_filter_th: -1

data:
  data_path: ../data/rna_data_0407/denoised_IM41441/cropped/tile_324/1
  codebook_path: ''
  # codebook_path: '../data/codebook.xlsx'

model:
  checkpoint_path: checkpoints
  save_gif: 0
  camera_z: -8
  step_z: 0.05
  num_slice: 46
  num_dims: 1

camera:
  cam_ids: [0, 1, 2, 3, 4]

view:
  classes:
  - 'Snap25'
  - 'Slc17a7'
  - 'Gad1'
  - 'Gad2'
  - 'Plp1'
  - 'Mbp'
  - 'Aqp4'
  - 'Rgs5'
  - 'Agt'
  - 'Chrm3'
  - 'Dclk3'
  - 'Necab1'
  - 'Cspg5'
  - 'Tnr'
  - 'Pdgfrb'
  - 'Anln'
  - 'Gfap'