exp_name: full_class_vis

train:
  lr: 0.005
  iterations: 20000
  num_primarys: 280000
  num_backups: 0
  tile_size: 16
  densification_start: 1000
  densification_interval: -2
  densification_th: 0.005
  model: fix_gauss
  codebook_start: 5000
  init_rgb: 1
  color_bias: 0.01

loss:
  w_l1: 0
  w_masked_l1: 1
  w_bg_l1: 1
  w_l2: 1
  w_masked_l2: 0
  w_bg_l2: 0
  w_mdp_l1: 0
  w_mdp_masked_l1: 1
  w_mdp_bg_l1: 1
  w_mdp_l2: 1
  w_mdp_masked_l2: 0
  w_mdp_bg_l2: 0

  w_rho: 0
  w_radius: 0
  w_mi: 0
  w_cos: 0

process:
  bg_filter_th: 0.05

data:
  data_path: ../data/IM41340_full/IM41340regi
  # data_path: ../data/IM41340_full/IM41340regi/2/3_4
  # data_path: ../data/IM41340_tiled/1_36
  codebook_path: ../data/codebook.xlsx

model:
  checkpoint_path: checkpoints
  save_gif: 0

view:
  classes:
  - 'Snap25'
  - 'Slc17a7'
  - 'Gad1'
  - 'Gad2'
  - 'plp1'
  - 'MBP'
  - 'Aqp4'
  - 'Rgs5'