exp_name: ori_full

train:
  lr: 0.004
  iterations: 10000
  num_samples: 8000
  tile_size: 16

loss:
  w_l1: 0
  w_l2: 1
  w_mi: 0
  w_masked_l2: 0
  w_bg_l2: 0
  w_masked_l1: 1
  w_bg_l1: 1
  w_rho: 0
  w_radius: 0

data:
  data_path: ../data/IM41340_tiled/1_36
  codebook_path: ../data/codebook.xlsx

model:
  checkpoint_path: checkpoints
  save_gif: 0
