exp_name: test_prune_th=5e-2_start=5k

train:
  lr: 0.005
  iterations: 20000
  num_primarys: 8000
  num_backups: 0
  tile_size: 16
  densification_start: 1000
  densification_interval: 200
  densification_th: 0.05

loss:
  w_l1: 0
  w_l2: 1
  w_masked_l2: 0
  w_bg_l2: 0
  w_masked_l1: 1
  w_bg_l1: 1
  w_rho: 0
  w_radius: 0
  w_mi: 0

data:
  # data_path: ../data/IM41340_full/IM41340regi
  data_path: ../data/IM41340_tiled/1_36
  codebook_path: ../data/codebook.xlsx

model:
  checkpoint_path: checkpoints
  save_gif: 0
