exp_name: step2_regcam_c128

train:
  lr: 0.002
  lr_cam: 0.001
  max_epochs: 3
  num_primarys: 800
  num_backups: 0
  tile_size: 16
  densification_start: 1000
  densification_interval: -2
  densification_th: 0.005
  model: fix_gauss
  codebook_start: 0
  init_rgb: 1
  color_bias: 0.01
  batch_size: 16
  num_per_epoch: 32000

loss:
  w_l1: 0
  w_masked_l1: 1
  w_bg_l1: 1
  w_l2: 1
  w_masked_l2: 0
  w_bg_l2: 0
  w_mdp_l1: 0
  w_mdp_masked_l1: 1
  w_mdp_bg_l1: 1
  w_mdp_l2: 1
  w_mdp_masked_l2: 0
  w_mdp_bg_l2: 0

  w_rho: 0
  w_radius: 0
  w_mi: 0
  w_cos: 0

process:
  bg_filter_th: -1

data:
  data_path: ../data/rna_data_0407/denoised_IM41441/cropped/tile_324/0
  codebook_path: ''
  # codebook_path: '../data/codebook.xlsx'

model:
  checkpoint_path: checkpoints
  save_gif: 0
  camera_z: -8
  step_z: 0.05
  max_num_slice: 50
  max_num_cams: 5
  num_dims: 3

camera:
  cam_ids: [1, 2, 3, 4]